### ISSUE TITLE
Basic endpoint requirements

### ISSUE THREAD

**Issue by ag4ums** [fossology/LicenseDb#1]
user roles : admin(write) and user :

### 1. License Endpoints
- [x] LicenseDb: Get all details /api/licenses:GET
- [x] LicenseDb: Get license by shortname/api/licenses/{license-shotname}:GET
- [x] LicenseDb: Update license /api/licenses/{license-shotname}:PATCH
- [x] LicenseDb: Create license /api/liceses/{license-shotname}:POST
- [x] LicenseDb: Get license modification details /api/liceses/{licese-shotname}/audit:GET
### 2. Search
- [x] LicenseDb: search in licensedb /api/licenses/search/{type: shortname, spdxid, licensetext }
### 3. User endpoints
- [x] LicenseDb: create user /api/users:POST
- [x] LicenseDb: users details /api/users:GET
- [x] LicenseDb: user details /api/users/{id}:GET
- [x] LicenseDb: JWT token only for admin users over api/token
### 4. Health Endpoints
- [x] LicenseDb: get health api/health
- [x] LicenseDb: get openapi doc /openapi?{type=json/yaml}

**Comment by Manthan109** [comment]
Hey, @ag4ums! I would be happy to contribute to this project.

**Comment by GarvitSinghal47** [comment]
hey @ag4ums i would like to contribute to this project .

**Comment by ag4ums** [comment]
@GarvitSinghal47 @Manthan109, Thank you for your interest in this project, but currently this is a GSoC23 project, you can only start contributing to this project once the GSoC23 is over ie after sept23.

**Comment by swetagit186** [comment]
Hello @ag4ums,I want to contribute to this project.

**Comment by swetagit186** [comment]
Hello @ag4ums,I want to contribute to this project.
