### ISSUE TITLE
Orchestration: LicenseDb needs docker support

### ISSUE THREAD

**Issue by deo002** [fossology/LicenseDb#63]
-  [ ] Create Dockerfile for LicenseDb. For details regarding Go version and other dependencies, please refer to the go.mod file. Keep port configurable.
-  [ ] In the compose file, setup containers for application and database(Postgresql). 

For more setup details, please refer to README.md file.

**Comment by Kaushl2208** [comment]
@deo002 , You can assign this to me!! Would like to work on it :)

**Comment by GMishx** [comment]
You can find the build and relevant run commands in the README
Also, check if you can use the "os less" images from Google. Will help us keep the total size small 😉

**Comment by k-avy** [comment]
Hi Gaurav, 
I have tried to add the dockerfile for LicenseDb. 
[Here](https://github.com/k-avy/LicenseDb/tree/dockerfile) is my work it may helps.

**Comment by avinal** [comment]
This was long due, glad to see ☺️
