### ISSUE TITLE
Create CI Action to build docker image

### ISSUE THREAD

**Issue by GMishx** [fossology/LicenseDb#66]
Create a GitHub Action to build and push docker image to Docker Hub.

Once the Action is available,
- [x] @GMishx to set authentication with Docker Hub

**Comment by Kaushl2208** [comment]
@GMishx , Looks like extension to my work. Will like to work on it :)

**Comment by GMishx** [comment]
Please go ahead @Kaushl2208

**Comment by GMishx** [comment]
The authentication is setup is done. Please reuse the relevant sections (make sure to use the correct variable names `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`) from FOSSology's build workflow

https://github.com/fossology/fossology/blob/f157388372376e7c496e3795314ef42551b3e912/.github/workflows/docker-build.yml#L35-L39
